export const CONTACT_SERVER_START = 'CONTACT_SERVER_START';
export const CONTACT_SERVER_SUCCESS = 'CONTACT_SERVER_SUCCESS';
export const CONTACT_SERVER_FAIL = 'CONTACT_SERVER_FAIL';
export const CLEAR_ACTIVE_VALUES = 'CLEAR_ACTIVE_VALUES';
//export const CHANGE_GRAPH_INTERVAL = 'CHANGE_GRAPH_INTERVAL';

export const CHANGE_ACTIVE_ROOM = 'CHANGE_ACTIVE_ROOM';

export const TOGGLE_NAV = 'TOGGLE_NAV';
