#!/bin/bash

clred="\033[0;31m"
clreset="\033[0m"

source <(cat "$(dirname $0)/../config" | egrep '^[a-z]+=(("[a-zA-Z0-9\.-]+")|([0-9]+))$')

desc="POST API testing utility. Usage: $(basename $0) [-v=version] -q=query [-f=file]
Current host: ${clred}$host:$port $clreset

Options:
  -v=version      API version, defaults to latest
  -q=query
  -f=file         Path to file containing data.
                  If no file is provided, read from STDIN."

for i in "$@"
do
case $i in
-v=*)
version=${i#*=}
shift
;;
-q=*)
query=${i#*=}
shift
;;
-f=*)
dfile=${i#*=}
;;
--help)
echo -e "$desc"
exit
;;
*)
;;
esac
done


if [ -z ${query+x} ]
then
echo -e "Missing query. Use ${clred}-q=query${clreset} argument."
exit 1
fi

if [ -z ${dfile+x} ]
then
data=$(cat -)
else
if [ -r $dfile ]
then
data=$(cat $dfile)
else
echo -e "\033[0;31mNo such file.\033[0m"
exit 1
fi
fi

if [ -z ${version+x} ]
then
version=$("$(dirname $0)/get-latest")
fi
echo "API version: $version"

echo "Connecting: $host:$port/api/v$version/$query"
curl -d "$data" -H "Content-Type: application/json" "$host:$port/api/v$version/$query"
